### ISSUE TITLE
ssh-config-keywords isn't found when installing noninteractively

### ISSUE THREAD

**Issue by jpkotta** [jhgorrell/ssh-config-mode-el#19]
If you install interactively, `load-file-name` is set correctly and the keywords file is found.  If you install non-interactively, e.g. you have a line like `(package-install 'ssh-config-mode)` or `(use-package ssh-config-mode)` in your init.el, `load-file-name` is not set to ssh-config-mode.el and the keywords file is not found. 

I think what I would do is make the keywords file an elisp file, something like `(defvar ssh-config-keywords '("kw1" "kw2" ...) "docstring")`.  Then you can `require` it at compile time and use Emacs's loading mechanism instead of trying to find the file.

**Comment by kkhan01** [comment]
I believe the problem lies at `ssh-config-load-file-dir`, which is also your proposed variable concept. Its value is set to my `~/.emacs.d` due to `default-directory`. My currently dirty hack until it's fixed (the package can't use it sadly, so I can't PR it):
```lisp
(use-package ssh-config-mode
  :init
  (setq ssh-config-load-file-dir (substring (find-library-name "ssh-config-mode") 0 -18)))
```
This will fail the first time the package is installed, but afterwards, it'll be fine, since the library path will exist. I'm not the best at elisp, but hopefully something better is figured out.

**Comment by sergeyklay** [comment]
Any new on this?

**Comment by andschwa** [comment]
Can any of you test if #24 fixes this for more than just me? It was a quick hack, but I think it works.

**Comment by jhgorrell** [comment]
Tried with "25.2.2" and "26.3" and wasnt able to reproduce the problem.

If I could get the emacs version and steps to reproduce the problem, that would be a big help.

**Comment by andschwa** [comment]
I'm using Emacs version:

```
GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109)) of 2019-09-02
```

And can repro it with this `test-init.el`:

```emacs-lisp
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
(package-refresh-contents)

(package-install 'ssh-config-mode)
```

Testing with:
```bash
emacs -Q -l test-init.el
```

Getting:
```
Leaving directory ‘/Users/andschwa/.emacs.d/elpa/ssh-config-mode-20191221.1051’
^L
Compiling file /Users/andschwa/.emacs.d/elpa/ssh-config-mode-20191221.1051/ssh-config-mode.el at Sat May  2 18:22:31 2020
Entering directory ‘/Users/andschwa/.emacs.d/elpa/ssh-config-mode-20191221.1051/’
ssh-config-mode.el:73:1:Error: Opening input file: No such file or directory, /Users/andschwa/ssh-config-keywords.txt
```

**Comment by jhgorrell** [comment]
Thank you so much for the test case - It really helped.

With that start, I made a bogus package archive for testing.
Think this should resolve the error.

**Comment by andschwa** [comment]
This fixes both the repro I provided you, and my own installation via a different package manager, [`straight.el`](https://github.com/raxod502/straight.el) (I just had to delete the old build of ssh-config-mode).

There's a funny side effect that `shs-config-keywords` appears that it originates in my `init.el` because it's defined when compiled, but its value is correct so I'm not complaining:

```
ssh-config-keywords is a variable defined in ‘init.el’.
Its value is
("AddKeysToAgent" ...
```

Thanks for fixing this @jhgorrell!
